### PR TITLE
Replace Timecode with Timestamp

### PR DESCRIPTION
**Pull request by onthegit**
Replace Timecode with Timestamp.

### CODE REVIEW

**Comment by davedoesdev** [comment]
I think the element name is mapped back from the ID here: https://github.com/oeuillot/node-matroska/blob/master/lib/schema.js#L537

So you can probably just change to:

```js
            else if (elm.type === "u" && elm.name === "Timestamp") {
```

**Comment by onthegit** [comment]
> I think the element name is mapped back from the ID here: https://github.com/oeuillot/node-matroska/blob/master/lib/schema.js#L537
> 
> So you can probably just change to:
> 
> ```js
>             else if (elm.type === "u" && elm.name === "Timestamp") {
> ```

Agreed

**Comment by davedoesdev** [comment]
Looks good. I think another problem was https://github.com/oeuillot/node-matroska/commit/d192c449c7e3de2748a6c149b5c191f0d1b29c3f should have bumped the major version of node-matroska.

**Comment by davedoesdev** [comment]
@onthegit I think I've done this too in #42 as part of a general deps update.
Would you mind checking please that I've covered it?

**Comment by onthegit** [comment]
Looks like changes were incorporated into your PR. Closing this.

**Pull request closed without merging**
