### PR TITLE
Create ts-ebml-min.js

### PR DESCRIPTION
**Pull request by guest271314**

### CODE REVIEW

**Comment by matthiasfostel** [comment]
Hey, would you mind explaining how you compiled this prior to mini-fying?

I have compiled the "official" ts-ebml using the npm script but the file produced in dist/ does not export ts-ebml like yours does and trying to figure out why.

**Comment by guest271314** [comment]
@matthiasfostel The code was compiled an unknown number of OS's ago. Do not have the exact procedure right now. Will browse notes to try and find the procedure. Observing the text it appears that used the `require()` function from https://gist.github.com/mathisonian/c325dbe02ea4d6880c4e and if recollect correctly `ts-ebml` from https://unpkg.com/browse/ts-ebml@2.0.2/.

See also https://github.com/guest271314/MediaFragmentRecorder/issues/8#issuecomment-520200727, et al.

**Comment by matthiasfostel** [comment]
Thank you for the quick response! I will go through your notes all to try to make a non-minified version usable for a Chrome extension and post the process here if you do not mind.

**Comment by guest271314** [comment]
Yes. Do so. Note also that `mkvmerge  `-o output.webm --enable-durations input.webm` is also capable of setting duration on  WebM and Matroska files, see https://github.com/guest271314/native-messaging-mkvmerge.

**Pull request closed without merging**
